### ISSUE TITLE
debug information

### ISSUE THREAD

**Issue by hoffoo** [jprante/elasticsearch-langdetect#27]
Is it possible to see debug logs for this plugin? I am seeing intermittent timeouts (longer than 5 seconds with small documents) with  and im trying to narrow down what could be causing it. I dont see anything langdetect related in the elasticsearch log. 

fwiw right after the timeout I can send it hundreds of requests and see it perform normally.

**Comment by jprante** [comment]
The detection is slow for long texts, for small documents it should be quick. I would be grateful for receiving an isolated test case with "evil" documents that might cause delays, for analysis.

**Comment by hoffoo** [comment]
Sadly I cant share the exact documents. I limited the docs sent to the first 4k hoping that was enough to still keep the search accurate. Ill increase how long we wait for a response, was just hoping to get some info in the log.

Thanks for a an awesome plugin!

**Comment by jprante** [comment]
N.B. there is not much to log on plugin level. There is a method call `detect()` which performs the heavy lifting. If you want to have the time spent in this method, I can add a debug statement of course.
