### ISSUE TITLE
Issue with Aggregations on language field

### ISSUE THREAD

**Issue by dobariya** [jprante/elasticsearch-langdetect#28]
Content.lang field does not give proper result when used in term aggregations having language zh-cn and zh-tw
I am using aggregations on content.lang filed as below

{
    "aggs" : {
        "tags" : {
             "terms" : {
                 "field" : "content.lang"
             }
         }
    }
}

the result is 

"aggregations": {
        "tags": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 5,
            "buckets": [
                {
                    "key": "zh",
                    "doc_count": 6
                },
                {
                    "key": "cn",
                    "doc_count": 4
                },
                {
                    "key": "en",
                    "doc_count": 4
                },
                {
                    "key": "ar",
                    "doc_count": 2
                },
                {
                    "key": "de",
                    "doc_count": 2
                },
                {
                    "key": "es",
                    "doc_count": 2
                },
                {
                    "key": "fr",
                    "doc_count": 2
                },
                {
                    "key": "ja",
                    "doc_count": 2
                },
                {
                    "key": "ko",
                    "doc_count": 2
                },
                {
                    "key": "no",
                    "doc_count": 2
                }
            ]
        }
    }

I have document with zh-cn and zh-tw language.When using aggregations it splits the word from "-" and makes two different words..See above output zh=6 and cn=4.But actually this is a single language "zh-cn"

Is this a bug? or do i have to set up anything else to make a whole word

**Comment by jprante** [comment]
New release 1.4.4.2 contains a bug fix. Thanks for reporting.
