### ISSUE TITLE
Plans for ES2.0?

### ISSUE THREAD

**Issue by mptei** [jprante/elasticsearch-langdetect#32]
Are you planning support for ES2.0? I've tried updating myself but it is to complicated for me, because there are many changes ...

**Comment by jprante** [comment]
I have bundled my plugins into one zip, and updated to 2.0.0-Beta1

Can you try https://github.com/jprante/elasticsearch-plugin-bundle ?

**Comment by mptei** [comment]
Thanks! I'll try this out.

**Comment by jprante** [comment]
Version 2.0.0.0 is released for ES 2.0.0
