### ISSUE TITLE
Which langdetect version is bundled along with Elasticsearch-plugin-bundle 5.1.1

### ISSUE THREAD

**Issue by antonsar** [jprante/elasticsearch-langdetect#52]
Hi JPrante, 

The Elasticsearch-plugin-bundle for ES 5.1.1 comes along with a lang-detect plugin.  I am interested only in the lang-detect plugin.  However the lang-detect repo only have version up to ES 2.4.  

So could we use the the lang-detect plugin for ES 2.4 with ES 5.1.1 ?
If not, is there a way to get only the lang-detect plugin from the Elasticsearch-plugin-bundle for ES 5.1.1 ?

Thank You

**Comment by jprante** [comment]
Thanks for the request. I will update the elasticsearch-langdetect plugin to 5.x

**Comment by antonsar** [comment]
Thank you very much, that will be great!

**Comment by jprante** [comment]
Version 5.1.2.0 for Elasticsearch 5.1.2 released.

There is one issue left with the REST API, the profile parameter does not work.

**Comment by antonsar** [comment]
Thank you very much JPrante, this is a great plugin!!
