### ISSUE TITLE
Detection problem with Unicode escaped JSON 

### ISSUE THREAD

**Issue by Nomadzy** [jprante/elasticsearch-langdetect#62]
If I POST some Unicode escaped Arabic text to the _langdetect endpoint, the plug-in detects it as Croatian.
Works fine with unescaped unicode json.

**Comment by jprante** [comment]
Please retry with latest version 5.3.2.0.

It should have been fixed with https://github.com/jprante/elasticsearch-langdetect/commit/b412faa16d14787331534342901724f9d95dccd9

**Comment by Nomadzy** [comment]
Thx a lot
